version: "3.8"

networks:
  app_network: # Define a custom network
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000 # Keep using backend hostname
    depends_on:
      - backend
    networks:
      - app_network # Attach to the network

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:password@postgres/weather_app
    depends_on:
      postgres:
        condition: service_healthy # ✅ Wait for PostgreSQL to be ready
    networks:
      - app_network

  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck: # ✅ Ensures PostgreSQL is ready before backend starts
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:
